CREATE TABLE IF NOT EXISTS secret (
    secret_id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash TEXT DEFAULT NULL UNIQUE,
    phrase TEXT DEFAULT NULL UNIQUE,
    created TEXT NOT NULL DEFAULT ( STRFTIME( '%Y-%m-%d %H:%M:%S:%s', 'NOW', 'LOCALTIME' ) )
);
